import React from "react";
import { ShieldCheck } from "lucide-react";

const CaseStudy1 = () => {
  return (
    <div className="space-y-6">
      <h1 className="text-3xl font-bold font-['Space_Grotesk'] text-gray-900 dark:text-white mb-2">
        Cloud Concurrency vs. Application Rate Limiting
      </h1>
      <div className="text-lg text-gray-600 dark:text-gray-300 leading-relaxed mb-6">
        How an unexpected 10,782 failure rate taught us the
        difference between Cloud Concurrency and Application Rate
        Limiting.
      </div>
      <h2 className="text-2xl font-bold font-['Outfit'] text-gray-900 dark:text-white border-l-4 border-indigo-500 pl-4 py-1">
        The Setup
      </h2>
      <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
        We deployed a dummy microservice on a standalone AWS EC2
        instance. This victim server was configured with a strict
        application-level rate limiter:{" "}
        <strong>10 requests per minute per IP address</strong>. To
        test our distributed architecture, we launched a Swarm of
        50 Virtual Users (AWS Lambdas) against the EC2 instance
        for exactly 10 seconds.
      </p>

      <h2 className="text-2xl font-bold font-['Outfit'] text-gray-900 dark:text-white border-l-4 border-indigo-500 pl-4 py-1">
        The Results
      </h2>
      <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
        The results were initially baffling. Out of 11,082
        requests generated by the orchestrator, only 100
        successfully reached the EC2 server. 200 were blocked by
        the EC2's rate limiter (HTTP 429), and a staggering{" "}
        <strong>10,782 requests failed entirely</strong> before
        even leaving the AWS cloud.
      </p>

      <h2 className="text-2xl font-bold font-['Outfit'] text-gray-900 dark:text-white border-l-4 border-indigo-500 pl-4 py-1">
        The Root Cause
      </h2>
      <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
        Two independent bottlenecks triggered simultaneously:
      </p>
      <ol className="text-gray-600 dark:text-gray-400 space-y-2">
        <li>
          <strong>AWS Unreserved Concurrency Limits:</strong> Our
          AWS account had a default concurrency limit of 10. When
          the orchestrator demanded 50 concurrent Lambda
          functions, AWS instantly rejected 40 of them. This
          resulted in the 10,782 failures as the local script
          desperately retried the rejected connections.
        </li>
        <li>
          <strong>
            Elastic Network Interface (ENI) IP Re-use:
          </strong>{" "}
          Because AWS only allowed 10 Lambda functions to spin up,
          those 10 functions were forced to rapidly fire requests.
          This means AWS <em>reused</em> the same 10 public IP
          addresses. The EC2 firewall easily detected that these
          10 IPs were firing more than 10 requests per minute, and
          blocked the overflow (the 200 HTTP 429 errors).
        </li>
      </ol>

      <div className="bg-indigo-50 dark:bg-[#6366f1]/10 border border-indigo-200 dark:border-[#6366f1]/30 rounded-2xl p-6 mt-8">
        <div className="flex items-center gap-3 mb-2">
          <ShieldCheck className="w-5 h-5 text-[#6366f1]" />
          <h4 className="font-bold text-gray-900 dark:text-white">
            The Lesson
          </h4>
        </div>
        <p className="text-gray-700 dark:text-gray-300 text-sm leading-relaxed">
          To successfully orchestrate a distributed load test that
          bypasses an enterprise WAF, you must have massive,
          unthrottled cloud concurrency. If your cloud provider
          limits your concurrency, your IPs will be reused, and
          the WAF will catch you.
        </p>
      </div>
    </div>
  );
};

export default CaseStudy1;
